theme: jekyll-theme-minimal
title: Emma Rogers
description: PhD Candidate in the Dept. of Earth Sciences at Dartmouth, working with advisor, Dr. Marisa Palucis, on developing a relationship between transport distance and clast morphometry at terrestrial analog sites for comparison to Mars.
logo: /img/IMG_8352.jpeg
baseurl: "/curriculum-vitae"
